### ISSUE TITLE
講義一覧の各項目に対してカーソルがポインターになってほしい

### ISSUE THREAD

**Issue by roottool** [ocw-central/ocw-central-frontend#123]
## 概要

講義ページ下部にある講義一覧の各項目にカーソルを合わせた時、カーソルがポインターになってほしいです！
自動書き起こしの各項目と同様に、講義一覧の各項目もクリックすると何かしらのアクションが発生するので。

## 対象

例えば[このページ](https://ocwcentral.com/subjects/01GB4X63GZBJWEZRZW2MJHH1Q9?video_id=01GF3N62T3KYVESW6RQKH9C1SV)のような、講義の動画が閲覧出来る講義ページ。
ファイルで言えば [src/components/SubjectPage.tsx](https://github.com/ocw-central/ocw-central-frontend/blob/main/src/components/SubjectPage.tsx)

## 期待する動作

自動書き起こしの各項目ように、講義一覧の各項目に対するカーソルがポインターになってほしい。
実装で言えば、下記の中に`cursor: 'pointer',`が追加されること。
https://github.com/ocw-central/ocw-central-frontend/blob/da1c6d1d7a18ffcf0c1498da2e35ffb793b761a9/src/components/subjectPageComponents/VideosBox.tsx#L45-L54

## 現在の動作

講義一覧の各項目にカーソルを合わせても、カーソルの表示が変わらない。

**Comment by yasutak** [comment]
詳細に説明いただきどうもありがとうございます。今日中に修正します。コメントを参考にissueのテンプレも追加します。
